name: my_baby_reveal
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.14.1
  lottie: ^2.7.0
  animated_flip_counter: ^0.2.6
  provider: ^6.1.1
  circular_countdown_timer: ^0.2.3
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/

  fonts:
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
