// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYek46-N6YEjhe49agvuhci903WEI03kI',
    appId: '1:731426910051:web:c5d449fdd162f55c4a2d56',
    messagingSenderId: '731426910051',
    projectId: 'my-baby-reveal',
    authDomain: 'my-baby-reveal.firebaseapp.com',
    storageBucket: 'my-baby-reveal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkk7iV0oAajz04IJoWsRIG7_HKWuh0_lU',
    appId: '1:731426910051:android:ede4b77cc6236e2f4a2d56',
    messagingSenderId: '731426910051',
    projectId: 'my-baby-reveal',
    storageBucket: 'my-baby-reveal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdvh25GP5p1-ry03HtbZCCqJGvWmzTPZ0',
    appId: '1:731426910051:ios:bb8a80fad297277e4a2d56',
    messagingSenderId: '731426910051',
    projectId: 'my-baby-reveal',
    storageBucket: 'my-baby-reveal.appspot.com',
    iosBundleId: 'com.example.myBabyReveal',
  );
}
